services:
  - type: web
    name: hdfs-anomaly-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: RAG_CSV_PATH
        value: results/rag_documents.csv

      - key: EMBEDDINGS_PATH
        value: results/embeddings.npy

      - key: CHROMA_DIR
        value: ./chroma_db
